version: "3"
services:

  client:
    build:
      context: ./client
    image: containerdemotsja.azurecr.io/client:1.0
    ports:
      - "3000:3000"
    
  api:
    build:
      context: ./DemoApi
    image: containerdemotsja.azurecr.io/api:1.0
    ports:
      - "5111:80"
