version: "3"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    image: containerdemotsja.azurecr.io/client:1.0
    ports:
      - "3000:3000"
  api:
    build:
      context: ./DemoAPI
    image: containerdemotsja.azurecr.io/api:1.0
    ports:
      - "5111:80"
