version: "3"
services:

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    image: cr.taklamakan.se/cdemo/client:1.0
    ports:
      - "3000:3000"
      
  api:
    build:
      context: ./api
    image: cr.taklamakan.se/cdemo/api:1.0
    ports:
      - "5111:80"

  