version: "3"
services:
  client:
    build:
      context: ./client
    image: client:1.0
    ports:
      - "3000:3000"
  api:
    build:
      context: ./DemoAPI
    image: api:1.0
    ports:
      - "5111:80"
