apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: container-demo-ingress
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: client
      port:
        number: 3000
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: client-service
            port:
              number: 3000

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: api-service
            port:
              number: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: container-demo-swagger-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: kubernetes.docker.internal
  - http:
      paths:
      - path: /swagger
        pathType: Prefix
        backend:
          service:
            name: api-service
            port:
              number: 80